require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UsuarioClientesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # UsuarioCliente. As you add validations to UsuarioCliente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsuarioClientesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all usuario_clientes as @usuario_clientes" do
      usuario_cliente = UsuarioCliente.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:usuario_clientes)).to eq([usuario_cliente])
    end
  end

  describe "GET show" do
    it "assigns the requested usuario_cliente as @usuario_cliente" do
      usuario_cliente = UsuarioCliente.create! valid_attributes
      get :show, {:id => usuario_cliente.to_param}, valid_session
      expect(assigns(:usuario_cliente)).to eq(usuario_cliente)
    end
  end

  describe "GET new" do
    it "assigns a new usuario_cliente as @usuario_cliente" do
      get :new, {}, valid_session
      expect(assigns(:usuario_cliente)).to be_a_new(UsuarioCliente)
    end
  end

  describe "GET edit" do
    it "assigns the requested usuario_cliente as @usuario_cliente" do
      usuario_cliente = UsuarioCliente.create! valid_attributes
      get :edit, {:id => usuario_cliente.to_param}, valid_session
      expect(assigns(:usuario_cliente)).to eq(usuario_cliente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UsuarioCliente" do
        expect {
          post :create, {:usuario_cliente => valid_attributes}, valid_session
        }.to change(UsuarioCliente, :count).by(1)
      end

      it "assigns a newly created usuario_cliente as @usuario_cliente" do
        post :create, {:usuario_cliente => valid_attributes}, valid_session
        expect(assigns(:usuario_cliente)).to be_a(UsuarioCliente)
        expect(assigns(:usuario_cliente)).to be_persisted
      end

      it "redirects to the created usuario_cliente" do
        post :create, {:usuario_cliente => valid_attributes}, valid_session
        expect(response).to redirect_to(UsuarioCliente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved usuario_cliente as @usuario_cliente" do
        post :create, {:usuario_cliente => invalid_attributes}, valid_session
        expect(assigns(:usuario_cliente)).to be_a_new(UsuarioCliente)
      end

      it "re-renders the 'new' template" do
        post :create, {:usuario_cliente => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested usuario_cliente" do
        usuario_cliente = UsuarioCliente.create! valid_attributes
        put :update, {:id => usuario_cliente.to_param, :usuario_cliente => new_attributes}, valid_session
        usuario_cliente.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested usuario_cliente as @usuario_cliente" do
        usuario_cliente = UsuarioCliente.create! valid_attributes
        put :update, {:id => usuario_cliente.to_param, :usuario_cliente => valid_attributes}, valid_session
        expect(assigns(:usuario_cliente)).to eq(usuario_cliente)
      end

      it "redirects to the usuario_cliente" do
        usuario_cliente = UsuarioCliente.create! valid_attributes
        put :update, {:id => usuario_cliente.to_param, :usuario_cliente => valid_attributes}, valid_session
        expect(response).to redirect_to(usuario_cliente)
      end
    end

    describe "with invalid params" do
      it "assigns the usuario_cliente as @usuario_cliente" do
        usuario_cliente = UsuarioCliente.create! valid_attributes
        put :update, {:id => usuario_cliente.to_param, :usuario_cliente => invalid_attributes}, valid_session
        expect(assigns(:usuario_cliente)).to eq(usuario_cliente)
      end

      it "re-renders the 'edit' template" do
        usuario_cliente = UsuarioCliente.create! valid_attributes
        put :update, {:id => usuario_cliente.to_param, :usuario_cliente => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested usuario_cliente" do
      usuario_cliente = UsuarioCliente.create! valid_attributes
      expect {
        delete :destroy, {:id => usuario_cliente.to_param}, valid_session
      }.to change(UsuarioCliente, :count).by(-1)
    end

    it "redirects to the usuario_clientes list" do
      usuario_cliente = UsuarioCliente.create! valid_attributes
      delete :destroy, {:id => usuario_cliente.to_param}, valid_session
      expect(response).to redirect_to(usuario_clientes_url)
    end
  end

end
